apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-vote-dev
  name: voting-vote-dev
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    load-balancer-voting-vote-dev: "true"
  sessionAffinity: None
  type: LoadBalancer
