apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-redis-canary
  name: voting-redis-canary
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    load-balancer-voting-redis-canary: "true"
  sessionAffinity: None
  type: ClusterIP
