apiVersion: v1
kind: PersistentVolume
metadata:
  name: voting-postgres-canary
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: voting-postgres-canary
    fsType: ext4
