apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-postgres-prod
  name: voting-postgres-prod
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    load-balancer-voting-postgres-prod: "true"
  sessionAffinity: None
  type: ClusterIP
